// src/store/slices/patientSlice.ts
import { createSlice, PayloadAction, createAsyncThunk } from "@reduxjs/toolkit";
import { RootState } from "../store/store";

// Define a type for a Patient. (Adjust this type to match your Patient model.)
export interface Patient {
  _id: string; // Automatically added by Mongoose (Document ID)
  userId: string; // Reference to the User model (stored as an ObjectID but used as a string in the interface)
  DoctorId: string; // Reference to the Doctor model
  ClinicId: string; // Reference to the Clinic model
  PatientId: string; // A unique patient identifier (e.g., "ES000001")
  fullName: string;
  contactNumber: string;
  gender: "Male" | "Female" | "Other";
  dateOfBirth: string; // Stored as a Date in MongoDB, but represented as a string (e.g., ISO format) in the interface
  address?: {
    street?: string;
    city?: string;
    state?: string;
    postalCode?: string;
  };
  medicalHistory?: string[]; // Array of strings
  currentMedications?: string[]; // Array of strings
  emergencyContact?: {
    fullName?: string;
    contactNumber?: string;
    relationship?: string;
  };
  createdAt: string; // Timestamp generated by Mongoose
  updatedAt: string; // Timestamp generated by Mongoose
}

interface PatientState {
  patients: Patient[];
  loading: boolean;
  error: string | null;
}

const initialState: PatientState = {
  patients: [],
  loading: false,
  error: null,
};

// Asynchronous thunk action for fetching patients
export const fetchPatients = createAsyncThunk(
  "patient/fetchPatients",
  async () => {
    const response = await fetch("/api/doctor/fetchPatients"); // Replace with your API route
    if (!response.ok) throw new Error("Failed to fetch patients");
    const data = await response.json();
    console.log(data);

    return data.patients as Patient[];
  }
);

const patientSlice = createSlice({
  name: "patient",
  initialState,
  reducers: {
    // Synchronous actions:
    addPatient(state, action: PayloadAction<Patient>) {
      state.patients.push(action.payload);
    },
    updatePatient(state, action: PayloadAction<Patient>) {
      const index = state.patients.findIndex(
        (patient) => patient._id === action.payload._id
      );
      if (index !== -1) {
        state.patients[index] = action.payload;
      }
    },
    deletePatient(state, action: PayloadAction<string>) {
      state.patients = state.patients.filter(
        (patient) => patient._id !== action.payload
      );
    },
  },
  extraReducers: (builder) => {
    builder
      .addCase(fetchPatients.pending, (state) => {
        state.loading = true;
        state.error = null;
      })
      .addCase(
        fetchPatients.fulfilled,
        (state, action: PayloadAction<Patient[]>) => {
          state.loading = false;
          state.patients = action.payload;
        }
      )
      .addCase(fetchPatients.rejected, (state, action) => {
        state.loading = false;
        state.error = action.error.message || "Failed to fetch patients";
      });
  },
});

export const { addPatient, updatePatient, deletePatient } =
  patientSlice.actions;
export const selectPatients = (state: RootState) => state.patient.patients;
export default patientSlice.reducer;
